""" calc_ui.py --

 UI generated by GUI Builder Build 146 on 2009-05-13 11:37:30 from:
    C:/projects/simplehsm/simplehsm_python/calc.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Calc(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._entry = Tkinter.Entry(root,
            width = 0,
        )
        self._button_7 = Tkinter.Button(root,
            text = 7,
            width = 3,
        )
        self._button_4 = Tkinter.Button(root,
            text = 4,
            width = 3,
        )
        self._button_1 = Tkinter.Button(root,
            text = 1,
            width = 3,
        )
        self._button_0 = Tkinter.Button(root,
            text = 0,
            width = 3,
        )
        self._button_8 = Tkinter.Button(root,
            text = 8,
            width = 3,
        )
        self._button_5 = Tkinter.Button(root,
            text = 5,
            width = 3,
        )
        self._button_2 = Tkinter.Button(root,
            text = 2,
            width = 3,
        )
        self._button_dot = Tkinter.Button(root,
            text = ".",
            width = 3,
        )
        self._button_9 = Tkinter.Button(root,
            text = 9,
            width = 3,
        )
        self._button_6 = Tkinter.Button(root,
            text = 6,
            width = 3,
        )
        self._button_3 = Tkinter.Button(root,
            text = 3,
            width = 3,
        )
        self._button_percent = Tkinter.Button(root,
            text = "%",
            width = 3,
        )
        self._button_divide = Tkinter.Button(root,
            text = "/",
            width = 3,
        )
        self._button_multiply = Tkinter.Button(root,
            text = "*",
            width = 3,
        )
        self._button_subtract = Tkinter.Button(root,
            text = "-",
            width = 3,
        )
        self._button_add = Tkinter.Button(root,
            text = "+",
            width = 3,
        )
        self._button_clear = Tkinter.Button(root,
            text = "C",
            width = 3,
        )
        self._button_clear_entry = Tkinter.Button(root,
            text = "CE",
            width = 3,
        )
        self._button_equals = Tkinter.Button(root,
            text = "=",
            width = 3,
        )

        # widget commands

        self._entry.configure(
            invalidcommand = self._entry_invalidcommand
        )
        self._entry.configure(
            validatecommand = self._entry_validatecommand
        )
        self._entry.configure(
            xscrollcommand = self._entry_xscrollcommand
        )
        self._button_7.configure(
            command = self._button_7_command
        )
        self._button_4.configure(
            command = self._button_4_command
        )
        self._button_1.configure(
            command = self._button_1_command
        )
        self._button_0.configure(
            command = self._button_0_command
        )
        self._button_8.configure(
            command = self._button_8_command
        )
        self._button_5.configure(
            command = self._button_5_command
        )
        self._button_2.configure(
            command = self._button_2_command
        )
        self._button_dot.configure(
            command = self._button_dot_command
        )
        self._button_9.configure(
            command = self._button_9_command
        )
        self._button_6.configure(
            command = self._button_6_command
        )
        self._button_3.configure(
            command = self._button_3_command
        )
        self._button_percent.configure(
            command = self._button_percent_command
        )
        self._button_divide.configure(
            command = self._button_divide_command
        )
        self._button_multiply.configure(
            command = self._button_multiply_command
        )
        self._button_subtract.configure(
            command = self._button_subtract_command
        )
        self._button_add.configure(
            command = self._button_add_command
        )
        self._button_clear.configure(
            command = self._button_clear_command
        )
        self._button_clear_entry.configure(
            command = self._button_clear_entry_command
        )
        self._button_equals.configure(
            command = self._button_equals_command
        )


        # Geometry Management
        self._entry.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 5,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._button_7.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_4.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_1.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_0.grid(
            in_    = root,
            column = 1,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_8.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_5.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_2.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_dot.grid(
            in_    = root,
            column = 2,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_9.grid(
            in_    = root,
            column = 3,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_6.grid(
            in_    = root,
            column = 3,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_3.grid(
            in_    = root,
            column = 3,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_percent.grid(
            in_    = root,
            column = 3,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_divide.grid(
            in_    = root,
            column = 4,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_multiply.grid(
            in_    = root,
            column = 4,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_subtract.grid(
            in_    = root,
            column = 4,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_add.grid(
            in_    = root,
            column = 4,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_clear.grid(
            in_    = root,
            column = 5,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_clear_entry.grid(
            in_    = root,
            column = 5,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_equals.grid(
            in_    = root,
            column = 5,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 18, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 13, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(5, weight = 0, minsize = 2, pad = 0)


